name: CI
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

            #      - name: Restore cache
            #        uses: actions/cache@v2
            #        with:
            #          path: ~/.cache/pip
            #          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            #          restore-keys: |
            #            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt install  python3-dev postgresql libpq-dev build-essential libxml2-dev libxslt1-dev postgresql
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
    
      - name: Setup database
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createuser --no-createrole --no-superuser --login \
          --inherit --createdb --pwprompt vulnerablecode
          sudo createdb --encoding=utf-8 --owner=vulnerablecode  --user=vulnerablecode \
          --host=localhost --port=5432 vulnerablecode

      - name: Run tests
        run: python -m pytest -v -m "not webtest"
        env:
          # The hostname, username used to communicate with the PostgreSQL service container
          POSTGRES_HOST: localhost
          VC_DB_USER: postgres
          POSTGRES_PORT: 5432
          DJANGO_DEV: 1
          GH_TOKEN: 1 
